### ISSUE TITLE
Work on test cases

### ISSUE THREAD

**Issue by halenander** [usfca-cs490-sp23/admissions-webhook#3]

**Comment by JacksonCrawford** [comment]
Commit 97632b913e7167014a4bbba7866917b95bde69a0 included basic test cases for the startup interface functionality

**Comment by JacksonCrawford** [comment]
Commit f4cf24fbf6cfdc16b7ffc4b2cdd95e912cf0b8ed added test cases for TLS generation and base64 encoding
